//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroAuctionApp.CoreViews.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EuroAuctionApp.CoreViews.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AddQuoteFile.
        /// </summary>
        internal static string AddQuoteFile {
            get {
                return ResourceManager.GetString("AddQuoteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AddQuoteFolder.
        /// </summary>
        internal static string AddQuoteFolder {
            get {
                return ResourceManager.GetString("AddQuoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AuctionPrice.
        /// </summary>
        internal static string AuctionPrice {
            get {
                return ResourceManager.GetString("AuctionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AuctionVolume.
        /// </summary>
        internal static string AuctionVolume {
            get {
                return ResourceManager.GetString("AuctionVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AuctionVolumePercent.
        /// </summary>
        internal static string AuctionVolumePercent {
            get {
                return ResourceManager.GetString("AuctionVolumePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AvgProfitInBP.
        /// </summary>
        internal static string AvgProfitInBP {
            get {
                return ResourceManager.GetString("AvgProfitInBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AvgProfitInPercent.
        /// </summary>
        internal static string AvgProfitInPercent {
            get {
                return ResourceManager.GetString("AvgProfitInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BackupAuctionFile.
        /// </summary>
        internal static string BackupAuctionFile {
            get {
                return ResourceManager.GetString("BackupAuctionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @BackupQuotes.
        /// </summary>
        internal static string BackupQuotes {
            get {
                return ResourceManager.GetString("BackupQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CalculateQuote.
        /// </summary>
        internal static string CalculateQuote {
            get {
                return ResourceManager.GetString("CalculateQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CleanAuction.
        /// </summary>
        internal static string CleanAuction {
            get {
                return ResourceManager.GetString("CleanAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CleanQuotes.
        /// </summary>
        internal static string CleanQuotes {
            get {
                return ResourceManager.GetString("CleanQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ClosePrice.
        /// </summary>
        internal static string ClosePrice {
            get {
                return ResourceManager.GetString("ClosePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CloseProfitInBP.
        /// </summary>
        internal static string CloseProfitInBP {
            get {
                return ResourceManager.GetString("CloseProfitInBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @CloseProfitInPercent.
        /// </summary>
        internal static string CloseProfitInPercent {
            get {
                return ResourceManager.GetString("CloseProfitInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ExploreAuctionFolder.
        /// </summary>
        internal static string ExploreAuctionFolder {
            get {
                return ResourceManager.GetString("ExploreAuctionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ExploreQuoteFolder.
        /// </summary>
        internal static string ExploreQuoteFolder {
            get {
                return ResourceManager.GetString("ExploreQuoteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ExportAuctionFile.
        /// </summary>
        internal static string ExportAuctionFile {
            get {
                return ResourceManager.GetString("ExportAuctionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @FileView.
        /// </summary>
        internal static string FileView {
            get {
                return ResourceManager.GetString("FileView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IdentifyQuotes.
        /// </summary>
        internal static string IdentifyQuotes {
            get {
                return ResourceManager.GetString("IdentifyQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Last5Price.
        /// </summary>
        internal static string Last5Price {
            get {
                return ResourceManager.GetString("Last5Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Last5ProfitInBP.
        /// </summary>
        internal static string Last5ProfitInBP {
            get {
                return ResourceManager.GetString("Last5ProfitInBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Last5ProfitInPercent.
        /// </summary>
        internal static string Last5ProfitInPercent {
            get {
                return ResourceManager.GetString("Last5ProfitInPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Last5Volume.
        /// </summary>
        internal static string Last5Volume {
            get {
                return ResourceManager.GetString("Last5Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Last5VolumePercent.
        /// </summary>
        internal static string Last5VolumePercent {
            get {
                return ResourceManager.GetString("Last5VolumePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Market.
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @OpenAuctionFile.
        /// </summary>
        internal static string OpenAuctionFile {
            get {
                return ResourceManager.GetString("OpenAuctionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @SqlView.
        /// </summary>
        internal static string SqlView {
            get {
                return ResourceManager.GetString("SqlView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @TotalVolume.
        /// </summary>
        internal static string TotalVolume {
            get {
                return ResourceManager.GetString("TotalVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @WriteToDb.
        /// </summary>
        internal static string WriteToDb {
            get {
                return ResourceManager.GetString("WriteToDb", resourceCulture);
            }
        }
    }
}
